-- Loaded only by playwright.auth.config.ts into an ephemeral local H2 database.
INSERT INTO SUBSCRIPTION_NOTICE (ID, SOURCE_SYSTEM, SOURCE_NOTICE_ID, HOUSING_CATEGORY, NOTICE_STATUS, TITLE, REGION_CODE, APPLY_START_DATE, APPLY_END_DATE, SYNCED_AT, FIRST_SEEN_AT, ROW_VERSION)
VALUES (900001, 'REB_APT', 'auth-browser-fixture', 'APARTMENT', 'OPEN', '로그인 유지 검증 주택', '서울', CURRENT_DATE, DATEADD('DAY', 30, CURRENT_DATE), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
