ALTER TABLE MEMBER_NOTIFICATION_PREFERENCE
    ADD COLUMN EMAIL_ENABLED BOOLEAN DEFAULT FALSE NOT NULL;

ALTER TABLE MEMBER_NOTIFICATION
    ADD COLUMN EMAIL_DELIVERY_REQUESTED BOOLEAN DEFAULT FALSE NOT NULL;

ALTER TABLE MEMBER_NOTIFICATION
    ADD COLUMN EMAIL_ATTEMPTS INTEGER DEFAULT 0 NOT NULL;

ALTER TABLE MEMBER_NOTIFICATION
    ADD COLUMN EMAIL_NEXT_ATTEMPT_AT TIMESTAMP WITH TIME ZONE;

ALTER TABLE MEMBER_NOTIFICATION
    ADD COLUMN EMAIL_SENT_AT TIMESTAMP WITH TIME ZONE;

ALTER TABLE MEMBER_NOTIFICATION
    ADD COLUMN EMAIL_LAST_ERROR VARCHAR(500);

ALTER TABLE MEMBER_NOTIFICATION
    ADD CONSTRAINT CK_MEMBER_NOTIFICATION_EMAIL_ATTEMPTS CHECK (EMAIL_ATTEMPTS >= 0);

CREATE INDEX IX_MEMBER_NOTIFICATION_EMAIL_QUEUE
    ON MEMBER_NOTIFICATION (
        EMAIL_DELIVERY_REQUESTED,
        EMAIL_SENT_AT,
        EMAIL_NEXT_ATTEMPT_AT,
        ID
    );
