CREATE SEQUENCE ADMIN_AUDIT_LOG_SEQ
    START WITH 1
    INCREMENT BY 1
    NO CYCLE;

CREATE TABLE ADMIN_AUDIT_LOG (
    ID BIGINT PRIMARY KEY,
    ACTOR_MEMBER_ID BIGINT NOT NULL,
    TARGET_MEMBER_ID BIGINT NOT NULL,
    AUDIT_ACTION VARCHAR(40) NOT NULL,
    AFFECTED_COUNT INTEGER DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT CK_ADMIN_AUDIT_ACTION CHECK (
        AUDIT_ACTION IN ('MEMBER_LOGIN_UNLOCKED', 'MEMBER_SESSIONS_REVOKED')
    ),
    CONSTRAINT CK_ADMIN_AUDIT_AFFECTED_COUNT CHECK (AFFECTED_COUNT >= 0),
    CONSTRAINT FK_ADMIN_AUDIT_ACTOR FOREIGN KEY (ACTOR_MEMBER_ID)
        REFERENCES APP_MEMBER (ID),
    CONSTRAINT FK_ADMIN_AUDIT_TARGET FOREIGN KEY (TARGET_MEMBER_ID)
        REFERENCES APP_MEMBER (ID)
);

CREATE INDEX IX_ADMIN_AUDIT_LOG_CREATED
    ON ADMIN_AUDIT_LOG (CREATED_AT DESC);

CREATE INDEX IX_ADMIN_AUDIT_LOG_TARGET
    ON ADMIN_AUDIT_LOG (TARGET_MEMBER_ID, CREATED_AT DESC);
