ALTER TABLE APP_MEMBER
    DROP CONSTRAINT CK_APP_MEMBER_STATUS;

ALTER TABLE APP_MEMBER
    ADD CONSTRAINT CK_APP_MEMBER_STATUS CHECK (
        MEMBER_STATUS IN ('ACTIVE', 'SUSPENDED', 'WITHDRAWN')
    );

ALTER TABLE APP_MEMBER
    ADD COLUMN SUSPENDED_AT TIMESTAMP WITH TIME ZONE;

ALTER TABLE APP_MEMBER
    ADD CONSTRAINT CK_APP_MEMBER_SUSPENDED_AT CHECK (
        MEMBER_STATUS <> 'SUSPENDED' OR SUSPENDED_AT IS NOT NULL
    );

ALTER TABLE ADMIN_AUDIT_LOG
    ADD COLUMN DETAILS VARCHAR(200);

ALTER TABLE ADMIN_AUDIT_LOG
    DROP CONSTRAINT CK_ADMIN_AUDIT_ACTION;

ALTER TABLE ADMIN_AUDIT_LOG
    ADD CONSTRAINT CK_ADMIN_AUDIT_ACTION CHECK (
        AUDIT_ACTION IN (
            'MEMBER_LOGIN_UNLOCKED',
            'MEMBER_SESSIONS_REVOKED',
            'MEMBER_SUSPENDED',
            'MEMBER_REACTIVATED'
        )
    );
