ALTER TABLE SUBSCRIPTION_NOTICE
    ADD COLUMN FIRST_SEEN_AT TIMESTAMP WITH TIME ZONE;

UPDATE SUBSCRIPTION_NOTICE
-- 배포 전에 이미 있던 공고가 신규 알림으로 한꺼번에 발송되지 않도록 이전 시각으로 초기화한다.
SET FIRST_SEEN_AT = CURRENT_TIMESTAMP - INTERVAL '1 day'
WHERE FIRST_SEEN_AT IS NULL;

ALTER TABLE SUBSCRIPTION_NOTICE
    ALTER COLUMN FIRST_SEEN_AT SET NOT NULL;

CREATE INDEX IX_NOTICE_FIRST_SEEN
    ON SUBSCRIPTION_NOTICE (FIRST_SEEN_AT);

ALTER TABLE MEMBER_NOTIFICATION_PREFERENCE
    ADD COLUMN NEW_MATCHING_NOTICE_ENABLED BOOLEAN DEFAULT TRUE NOT NULL;

ALTER TABLE MEMBER_NOTIFICATION
    DROP CONSTRAINT CK_MEMBER_NOTIFICATION_TYPE;

ALTER TABLE MEMBER_NOTIFICATION
    ADD CONSTRAINT CK_MEMBER_NOTIFICATION_TYPE CHECK (
        NOTIFICATION_TYPE IN (
            'APPLY_START',
            'APPLY_DEADLINE_7D',
            'APPLY_DEADLINE_3D',
            'APPLY_DEADLINE_1D',
            'WINNER_ANNOUNCEMENT',
            'NEW_MATCHING_NOTICE'
        )
    );
