ALTER TABLE SUBSCRIPTION_NOTICE
    ADD COLUMN POSTAL_CODE VARCHAR(10);
ALTER TABLE SUBSCRIPTION_NOTICE
    ADD COLUMN HOUSING_DETAIL_TYPE VARCHAR(100);
ALTER TABLE SUBSCRIPTION_NOTICE
    ADD COLUMN RENT_TYPE VARCHAR(100);
ALTER TABLE SUBSCRIPTION_NOTICE
    ADD COLUMN BUSINESS_ENTITY_NAME VARCHAR(300);
ALTER TABLE SUBSCRIPTION_NOTICE
    ADD COLUMN CONSTRUCTION_COMPANY_NAME VARCHAR(500);
ALTER TABLE SUBSCRIPTION_NOTICE
    ADD COLUMN CONTACT_PHONE VARCHAR(50);
ALTER TABLE SUBSCRIPTION_NOTICE
    ADD COLUMN HOMEPAGE_URL VARCHAR(1000);
ALTER TABLE SUBSCRIPTION_NOTICE
    ADD COLUMN MOVE_IN_PLANNED_MONTH VARCHAR(20);
ALTER TABLE SUBSCRIPTION_NOTICE
    ADD COLUMN SPECIAL_SUPPLY_START_DATE DATE;
ALTER TABLE SUBSCRIPTION_NOTICE
    ADD COLUMN SPECIAL_SUPPLY_END_DATE DATE;
ALTER TABLE SUBSCRIPTION_NOTICE
    ADD COLUMN CONTRACT_START_DATE DATE;
ALTER TABLE SUBSCRIPTION_NOTICE
    ADD COLUMN CONTRACT_END_DATE DATE;
