ALTER TABLE SUBSCRIPTION_NOTICE
    ADD COLUMN POSTAL_CODE VARCHAR(10),
    ADD COLUMN HOUSING_DETAIL_TYPE VARCHAR(100),
    ADD COLUMN RENT_TYPE VARCHAR(100),
    ADD COLUMN BUSINESS_ENTITY_NAME VARCHAR(300),
    ADD COLUMN CONSTRUCTION_COMPANY_NAME VARCHAR(500),
    ADD COLUMN CONTACT_PHONE VARCHAR(50),
    ADD COLUMN HOMEPAGE_URL VARCHAR(1000),
    ADD COLUMN MOVE_IN_PLANNED_MONTH VARCHAR(20),
    ADD COLUMN SPECIAL_SUPPLY_START_DATE DATE,
    ADD COLUMN SPECIAL_SUPPLY_END_DATE DATE,
    ADD COLUMN CONTRACT_START_DATE DATE,
    ADD COLUMN CONTRACT_END_DATE DATE;
