ALTER TABLE SUBSCRIPTION_NOTICE
    ADD COLUMN CONTENT_CHANGED_AT TIMESTAMP WITH TIME ZONE;

CREATE INDEX IX_NOTICE_CONTENT_CHANGED
    ON SUBSCRIPTION_NOTICE (CONTENT_CHANGED_AT);

ALTER TABLE MEMBER_NOTIFICATION_PREFERENCE
    ADD COLUMN NOTICE_UPDATED_ENABLED BOOLEAN DEFAULT TRUE NOT NULL;

ALTER TABLE MEMBER_NOTIFICATION
    DROP CONSTRAINT CK_MEMBER_NOTIFICATION_TYPE;

ALTER TABLE MEMBER_NOTIFICATION
    ADD CONSTRAINT CK_MEMBER_NOTIFICATION_TYPE CHECK (
        NOTIFICATION_TYPE IN (
            'APPLY_START',
            'APPLY_DEADLINE_7D',
            'APPLY_DEADLINE_3D',
            'APPLY_DEADLINE_1D',
            'WINNER_ANNOUNCEMENT',
            'NEW_MATCHING_NOTICE',
            'NOTICE_UPDATED'
        )
    );
