CREATE SEQUENCE NOTICE_CHANGE_HISTORY_SEQ START WITH 1 INCREMENT BY 50;

CREATE TABLE NOTICE_CHANGE_HISTORY (
    ID BIGINT PRIMARY KEY,
    NOTICE_ID BIGINT NOT NULL,
    CHANGE_SUMMARY VARCHAR(500) NOT NULL,
    CHANGED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT FK_NOTICE_CHANGE_NOTICE FOREIGN KEY (NOTICE_ID) REFERENCES SUBSCRIPTION_NOTICE (ID) ON DELETE CASCADE,
    CONSTRAINT UK_NOTICE_CHANGE_TIME UNIQUE (NOTICE_ID, CHANGED_AT)
);

CREATE INDEX IX_NOTICE_CHANGE_NOTICE_TIME ON NOTICE_CHANGE_HISTORY (NOTICE_ID, CHANGED_AT DESC);
