CREATE SEQUENCE MEMBER_ELIGIBILITY_PROFILE_SEQ
    START WITH 1
    INCREMENT BY 1
    NO CYCLE;

CREATE TABLE MEMBER_ELIGIBILITY_PROFILE (
    ID BIGINT PRIMARY KEY,
    MEMBER_ID BIGINT NOT NULL,
    HOMELESS_ANSWER VARCHAR(10) NOT NULL,
    SUBSCRIPTION_ACCOUNT_ANSWER VARCHAR(10) NOT NULL,
    NEWLYWED_ANSWER VARCHAR(10) NOT NULL,
    FIRST_HOME_ANSWER VARCHAR(10) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT UK_MEMBER_ELIGIBILITY_PROFILE UNIQUE (MEMBER_ID),
    CONSTRAINT FK_MEMBER_ELIGIBILITY_MEMBER FOREIGN KEY (MEMBER_ID)
        REFERENCES APP_MEMBER (ID) ON DELETE CASCADE,
    CONSTRAINT CK_MEMBER_ELIGIBILITY_HOMELESS CHECK (HOMELESS_ANSWER IN ('YES', 'NO', 'UNKNOWN')),
    CONSTRAINT CK_MEMBER_ELIGIBILITY_ACCOUNT CHECK (SUBSCRIPTION_ACCOUNT_ANSWER IN ('YES', 'NO', 'UNKNOWN')),
    CONSTRAINT CK_MEMBER_ELIGIBILITY_NEWLYWED CHECK (NEWLYWED_ANSWER IN ('YES', 'NO', 'UNKNOWN')),
    CONSTRAINT CK_MEMBER_ELIGIBILITY_FIRST_HOME CHECK (FIRST_HOME_ANSWER IN ('YES', 'NO', 'UNKNOWN'))
);
