ALTER TABLE SYNC_EXECUTION
    DROP CONSTRAINT CK_SYNC_EXECUTION_STATUS;

ALTER TABLE SYNC_EXECUTION
    ADD CONSTRAINT CK_SYNC_EXECUTION_STATUS CHECK (
        STATUS IN ('RUNNING', 'SUCCEEDED', 'PARTIALLY_SUCCEEDED', 'FAILED')
    );
