CREATE SEQUENCE SUBSCRIPTION_NOTICE_SEQ
    START WITH 1
    INCREMENT BY 50
    CACHE 50
    NO CYCLE;

CREATE TABLE SUBSCRIPTION_NOTICE (
    ID                      BIGINT          NOT NULL,
    SOURCE_SYSTEM           VARCHAR(30)     NOT NULL,
    SOURCE_NOTICE_ID        VARCHAR(80)     NOT NULL,
    HOUSING_CATEGORY        VARCHAR(30)     NOT NULL,
    NOTICE_STATUS           VARCHAR(20)     NOT NULL,
    TITLE                   VARCHAR(300)    NOT NULL,
    REGION_CODE             VARCHAR(20),
    ADDRESS                 VARCHAR(500),
    NOTICE_DATE             DATE,
    APPLY_START_DATE        DATE,
    APPLY_END_DATE          DATE,
    WINNER_ANNOUNCE_DATE    DATE,
    TOTAL_UNITS             INTEGER,
    MIN_PRICE               NUMERIC(18),
    MAX_PRICE               NUMERIC(18),
    OFFICIAL_URL            VARCHAR(1000),
    CONTENT_HASH            VARCHAR(64),
    SYNCED_AT               TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    ROW_VERSION             BIGINT DEFAULT 0 NOT NULL,
    CONSTRAINT PK_SUBSCRIPTION_NOTICE PRIMARY KEY (ID),
    CONSTRAINT UK_NOTICE_SOURCE UNIQUE (SOURCE_SYSTEM, SOURCE_NOTICE_ID),
    CONSTRAINT CK_NOTICE_CATEGORY CHECK (
        HOUSING_CATEGORY IN ('APARTMENT', 'PUBLIC_RENTAL', 'OFFICETEL')
    ),
    CONSTRAINT CK_NOTICE_STATUS CHECK (
        NOTICE_STATUS IN ('UPCOMING', 'OPEN', 'CLOSED', 'ANNOUNCED')
    )
);

CREATE INDEX IX_NOTICE_CATEGORY_STATUS
    ON SUBSCRIPTION_NOTICE (HOUSING_CATEGORY, NOTICE_STATUS);

CREATE INDEX IX_NOTICE_APPLY_PERIOD
    ON SUBSCRIPTION_NOTICE (APPLY_START_DATE, APPLY_END_DATE);

CREATE INDEX IX_NOTICE_REGION
    ON SUBSCRIPTION_NOTICE (REGION_CODE);

CREATE SEQUENCE SYNC_EXECUTION_SEQ
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NO CYCLE;

CREATE TABLE SYNC_EXECUTION (
    ID              BIGINT          NOT NULL,
    STATUS          VARCHAR(20)     NOT NULL,
    STARTED_AT      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    FINISHED_AT     TIMESTAMP(6) WITH TIME ZONE,
    FETCHED_COUNT   INTEGER DEFAULT 0 NOT NULL,
    SAVED_COUNT     INTEGER DEFAULT 0 NOT NULL,
    ERROR_MESSAGE   VARCHAR(2000),
    CONSTRAINT PK_SYNC_EXECUTION PRIMARY KEY (ID),
    CONSTRAINT CK_SYNC_EXECUTION_STATUS CHECK (
        STATUS IN ('RUNNING', 'SUCCEEDED', 'FAILED')
    )
);

CREATE INDEX IX_SYNC_EXECUTION_STARTED
    ON SYNC_EXECUTION (STARTED_AT DESC);
