ALTER TABLE APP_MEMBER ADD COLUMN BIRTH_DATE DATE;
ALTER TABLE APP_MEMBER ADD COLUMN GENDER VARCHAR(20);
ALTER TABLE APP_MEMBER ADD COLUMN MARITAL_STATUS VARCHAR(20);
ALTER TABLE APP_MEMBER ADD COLUMN HOUSEHOLD_MEMBER_COUNT INTEGER;
ALTER TABLE APP_MEMBER ADD COLUMN CHILD_COUNT INTEGER;
ALTER TABLE APP_MEMBER ADD COLUMN RESIDENCE_REGION VARCHAR(20);

ALTER TABLE APP_MEMBER ADD CONSTRAINT CK_APP_MEMBER_GENDER
    CHECK (GENDER IS NULL OR GENDER IN ('MALE', 'FEMALE', 'OTHER'));
ALTER TABLE APP_MEMBER ADD CONSTRAINT CK_APP_MEMBER_MARITAL_STATUS
    CHECK (MARITAL_STATUS IS NULL OR MARITAL_STATUS IN ('SINGLE', 'MARRIED'));
ALTER TABLE APP_MEMBER ADD CONSTRAINT CK_APP_MEMBER_HOUSEHOLD_COUNT
    CHECK (HOUSEHOLD_MEMBER_COUNT IS NULL OR HOUSEHOLD_MEMBER_COUNT BETWEEN 1 AND 20);
ALTER TABLE APP_MEMBER ADD CONSTRAINT CK_APP_MEMBER_CHILD_COUNT
    CHECK (CHILD_COUNT IS NULL OR CHILD_COUNT BETWEEN 0 AND 20);
