ALTER TABLE MEMBER_SEARCH_PREFERENCE ADD COLUMN MIN_PRICE_MANWON INTEGER;
ALTER TABLE MEMBER_SEARCH_PREFERENCE ADD COLUMN MAX_PRICE_MANWON INTEGER;
ALTER TABLE MEMBER_SEARCH_PREFERENCE ADD CONSTRAINT CK_MEMBER_SEARCH_MIN_PRICE_MANWON
    CHECK (MIN_PRICE_MANWON IS NULL OR MIN_PRICE_MANWON >= 0);
ALTER TABLE MEMBER_SEARCH_PREFERENCE ADD CONSTRAINT CK_MEMBER_SEARCH_MAX_PRICE_MANWON
    CHECK (MAX_PRICE_MANWON IS NULL OR MAX_PRICE_MANWON >= 0);
ALTER TABLE MEMBER_SEARCH_PREFERENCE ADD CONSTRAINT CK_MEMBER_SEARCH_PRICE_RANGE
    CHECK (MIN_PRICE_MANWON IS NULL OR MAX_PRICE_MANWON IS NULL OR MIN_PRICE_MANWON <= MAX_PRICE_MANWON);
