ALTER TABLE MEMBER_FAVORITE ADD COLUMN PROGRESS VARCHAR(20) NOT NULL DEFAULT 'SAVED';
ALTER TABLE MEMBER_FAVORITE ADD COLUMN MEMO VARCHAR(500);
ALTER TABLE MEMBER_FAVORITE ADD COLUMN UPDATED_AT TIMESTAMP WITH TIME ZONE;
UPDATE MEMBER_FAVORITE SET UPDATED_AT = CREATED_AT WHERE UPDATED_AT IS NULL;
ALTER TABLE MEMBER_FAVORITE ALTER COLUMN UPDATED_AT SET NOT NULL;
ALTER TABLE MEMBER_FAVORITE ADD CONSTRAINT CK_MEMBER_FAVORITE_PROGRESS
    CHECK (PROGRESS IN ('SAVED', 'CHECKING', 'READY', 'APPLIED'));
