ALTER TABLE MEMBER_FAVORITE ADD COLUMN NOTICE_DOCUMENT_CHECKED BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE MEMBER_FAVORITE ADD COLUMN ELIGIBILITY_CHECKED BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE MEMBER_FAVORITE ADD COLUMN SCHEDULE_CHECKED BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE MEMBER_FAVORITE ADD COLUMN FUNDS_CHECKED BOOLEAN NOT NULL DEFAULT FALSE;
