CREATE SEQUENCE MEMBER_DEVICE_TOKEN_SEQ
    START WITH 1
    INCREMENT BY 1
    NO CYCLE;

CREATE TABLE MEMBER_DEVICE_TOKEN (
    ID BIGINT PRIMARY KEY,
    MEMBER_ID BIGINT NOT NULL,
    PUSH_TOKEN VARCHAR(512) NOT NULL,
    PLATFORM VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    LAST_SEEN_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT UK_MEMBER_DEVICE_TOKEN UNIQUE (PUSH_TOKEN),
    CONSTRAINT FK_MEMBER_DEVICE_TOKEN_MEMBER FOREIGN KEY (MEMBER_ID)
        REFERENCES APP_MEMBER (ID) ON DELETE CASCADE,
    CONSTRAINT CK_MEMBER_DEVICE_TOKEN_PLATFORM CHECK (PLATFORM IN ('ANDROID', 'IOS'))
);

CREATE INDEX IX_MEMBER_DEVICE_TOKEN_MEMBER ON MEMBER_DEVICE_TOKEN (MEMBER_ID);

ALTER TABLE MEMBER_NOTIFICATION_PREFERENCE
    ADD COLUMN APP_PUSH_ENABLED BOOLEAN DEFAULT TRUE NOT NULL;
