ALTER TABLE MEMBER_NOTIFICATION ADD COLUMN PUSH_DELIVERY_REQUESTED BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE MEMBER_NOTIFICATION ADD COLUMN PUSH_ATTEMPTS INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE MEMBER_NOTIFICATION ADD COLUMN PUSH_NEXT_ATTEMPT_AT TIMESTAMP WITH TIME ZONE;
ALTER TABLE MEMBER_NOTIFICATION ADD COLUMN PUSH_SENT_AT TIMESTAMP WITH TIME ZONE;
ALTER TABLE MEMBER_NOTIFICATION ADD COLUMN PUSH_LAST_ERROR VARCHAR(500);

CREATE INDEX IX_MEMBER_NOTIFICATION_PUSH_DELIVERY
    ON MEMBER_NOTIFICATION (PUSH_DELIVERY_REQUESTED, PUSH_SENT_AT, PUSH_NEXT_ATTEMPT_AT);
