CREATE SEQUENCE MEMBER_POLICY_CONSENT_SEQ START WITH 1 INCREMENT BY 1 NO CYCLE;

CREATE TABLE MEMBER_POLICY_CONSENT (
    ID BIGINT PRIMARY KEY,
    MEMBER_ID BIGINT NOT NULL,
    POLICY_TYPE VARCHAR(30) NOT NULL,
    POLICY_VERSION VARCHAR(30) NOT NULL,
    AGREED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT FK_MEMBER_POLICY_CONSENT_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES APP_MEMBER (ID) ON DELETE CASCADE,
    CONSTRAINT UK_MEMBER_POLICY_CONSENT UNIQUE (MEMBER_ID, POLICY_TYPE, POLICY_VERSION)
);
CREATE INDEX IX_MEMBER_POLICY_CONSENT_MEMBER ON MEMBER_POLICY_CONSENT (MEMBER_ID);
