CREATE SEQUENCE APP_MEMBER_SEQ
    START WITH 1
    INCREMENT BY 1
    NO CYCLE;

CREATE SEQUENCE MEMBER_LOGIN_SESSION_SEQ
    START WITH 1
    INCREMENT BY 1
    NO CYCLE;

CREATE SEQUENCE MEMBER_FAVORITE_SEQ
    START WITH 1
    INCREMENT BY 1
    NO CYCLE;

CREATE TABLE APP_MEMBER (
    ID BIGINT PRIMARY KEY,
    EMAIL VARCHAR(320) NOT NULL,
    PASSWORD_HASH VARCHAR(100) NOT NULL,
    NICKNAME VARCHAR(40) NOT NULL,
    MEMBER_STATUS VARCHAR(20) NOT NULL,
    FAILED_LOGIN_ATTEMPTS INTEGER DEFAULT 0 NOT NULL,
    LOCKED_UNTIL TIMESTAMP WITH TIME ZONE,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    WITHDRAWN_AT TIMESTAMP WITH TIME ZONE,
    CONSTRAINT UK_APP_MEMBER_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CK_APP_MEMBER_STATUS CHECK (MEMBER_STATUS IN ('ACTIVE', 'WITHDRAWN')),
    CONSTRAINT CK_APP_MEMBER_LOGIN_ATTEMPTS CHECK (FAILED_LOGIN_ATTEMPTS >= 0)
);

CREATE TABLE MEMBER_LOGIN_SESSION (
    ID BIGINT PRIMARY KEY,
    MEMBER_ID BIGINT NOT NULL,
    TOKEN_HASH VARCHAR(64) NOT NULL,
    EXPIRES_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT UK_MEMBER_SESSION_TOKEN UNIQUE (TOKEN_HASH),
    CONSTRAINT FK_MEMBER_SESSION_MEMBER FOREIGN KEY (MEMBER_ID)
        REFERENCES APP_MEMBER (ID) ON DELETE CASCADE
);

CREATE INDEX IX_MEMBER_SESSION_MEMBER ON MEMBER_LOGIN_SESSION (MEMBER_ID);
CREATE INDEX IX_MEMBER_SESSION_EXPIRY ON MEMBER_LOGIN_SESSION (EXPIRES_AT);

CREATE TABLE MEMBER_FAVORITE (
    ID BIGINT PRIMARY KEY,
    MEMBER_ID BIGINT NOT NULL,
    NOTICE_ID BIGINT NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT UK_MEMBER_FAVORITE UNIQUE (MEMBER_ID, NOTICE_ID),
    CONSTRAINT FK_MEMBER_FAVORITE_MEMBER FOREIGN KEY (MEMBER_ID)
        REFERENCES APP_MEMBER (ID) ON DELETE CASCADE,
    CONSTRAINT FK_MEMBER_FAVORITE_NOTICE FOREIGN KEY (NOTICE_ID)
        REFERENCES SUBSCRIPTION_NOTICE (ID) ON DELETE CASCADE
);

CREATE INDEX IX_MEMBER_FAVORITE_MEMBER ON MEMBER_FAVORITE (MEMBER_ID);
