CREATE SEQUENCE MEMBER_SAVED_SEARCH_PROFILE_SEQ START WITH 1 INCREMENT BY 1 NO CYCLE;
CREATE TABLE MEMBER_SAVED_SEARCH_PROFILE (
  ID BIGINT PRIMARY KEY, MEMBER_ID BIGINT NOT NULL, PROFILE_NAME VARCHAR(40) NOT NULL,
  REGION VARCHAR(40), HOUSING_CATEGORY VARCHAR(20), STATUS_FILTER VARCHAR(20) NOT NULL, SORT_OPTION VARCHAR(20) NOT NULL,
  MIN_PRICE_MANWON INTEGER, MAX_PRICE_MANWON INTEGER, CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL, UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT FK_MEMBER_SAVED_SEARCH_PROFILE_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES APP_MEMBER (ID) ON DELETE CASCADE,
  CONSTRAINT UK_MEMBER_SAVED_SEARCH_PROFILE_NAME UNIQUE (MEMBER_ID, PROFILE_NAME)
);
CREATE INDEX IX_MEMBER_SAVED_SEARCH_PROFILE_MEMBER ON MEMBER_SAVED_SEARCH_PROFILE (MEMBER_ID);
