ALTER TABLE MEMBER_SAVED_SEARCH_PROFILE ADD COLUMN IS_DEFAULT BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE MEMBER_SAVED_SEARCH_PROFILE ADD COLUMN NEW_NOTICE_ENABLED BOOLEAN NOT NULL DEFAULT TRUE;
CREATE INDEX IX_MEMBER_SAVED_SEARCH_PROFILE_DEFAULT ON MEMBER_SAVED_SEARCH_PROFILE (MEMBER_ID, IS_DEFAULT);
