CREATE SEQUENCE SUBSCRIPTION_NOTICE_UNIT_TYPE_SEQ
    START WITH 1
    INCREMENT BY 50
    CACHE 50
    NO CYCLE;

CREATE TABLE SUBSCRIPTION_NOTICE_UNIT_TYPE (
    ID                  BIGINT          NOT NULL,
    NOTICE_ID           BIGINT          NOT NULL,
    SOURCE_MODEL_ID     VARCHAR(100)    NOT NULL,
    HOUSING_TYPE_NAME   VARCHAR(100)    NOT NULL,
    SUPPLY_AREA         NUMERIC(10, 2),
    GENERAL_SUPPLY_COUNT INTEGER,
    SPECIAL_SUPPLY_COUNT INTEGER,
    TOTAL_SUPPLY_COUNT   INTEGER,
    MAX_PRICE           NUMERIC(18),
    SYNCED_AT           TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT PK_NOTICE_UNIT_TYPE PRIMARY KEY (ID),
    CONSTRAINT UK_NOTICE_UNIT_TYPE UNIQUE (NOTICE_ID, SOURCE_MODEL_ID),
    CONSTRAINT FK_NOTICE_UNIT_TYPE_NOTICE FOREIGN KEY (NOTICE_ID) REFERENCES SUBSCRIPTION_NOTICE (ID) ON DELETE CASCADE
);

CREATE INDEX IX_NOTICE_UNIT_TYPE_NOTICE ON SUBSCRIPTION_NOTICE_UNIT_TYPE (NOTICE_ID);
