ALTER TABLE MEMBER_SEARCH_PREFERENCE ADD COLUMN SUPPLY_TYPE VARCHAR(20);
ALTER TABLE MEMBER_SEARCH_PREFERENCE ADD COLUMN MIN_AREA NUMERIC(10, 2);
ALTER TABLE MEMBER_SEARCH_PREFERENCE ADD COLUMN MAX_AREA NUMERIC(10, 2);

ALTER TABLE MEMBER_SAVED_SEARCH_PROFILE ADD COLUMN SUPPLY_TYPE VARCHAR(20);
ALTER TABLE MEMBER_SAVED_SEARCH_PROFILE ADD COLUMN MIN_AREA NUMERIC(10, 2);
ALTER TABLE MEMBER_SAVED_SEARCH_PROFILE ADD COLUMN MAX_AREA NUMERIC(10, 2);
