-- No prompts, answers, credentials or raw device tokens are stored here.
CREATE TABLE AI_CONSULTATION_GATE (ID INTEGER PRIMARY KEY);
INSERT INTO AI_CONSULTATION_GATE (ID) VALUES (1);
CREATE TABLE AI_CONSULTATION_ATTEMPT (
    ID VARCHAR(36) PRIMARY KEY,
    MEMBER_ID BIGINT NOT NULL,
    STARTED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    FINISHED_AT TIMESTAMP WITH TIME ZONE,
    STATUS VARCHAR(16) NOT NULL CHECK (STATUS IN ('ACTIVE', 'SUCCESS', 'FAILED', 'ABANDONED'))
);
CREATE INDEX IX_AI_ATTEMPT_STARTED ON AI_CONSULTATION_ATTEMPT (STARTED_AT);
CREATE INDEX IX_AI_ATTEMPT_MEMBER ON AI_CONSULTATION_ATTEMPT (MEMBER_ID, STARTED_AT);
CREATE TABLE MEMBER_PUSH_RECEIPT (
    NOTIFICATION_ID BIGINT NOT NULL REFERENCES MEMBER_NOTIFICATION(ID) ON DELETE CASCADE,
    TOKEN_HASH VARCHAR(64) NOT NULL,
    COMPLETED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (NOTIFICATION_ID, TOKEN_HASH)
);
