-- Nullable additions preserve legacy records without guessing delivery success.
ALTER TABLE MEMBER_PUSH_RECEIPT ADD COLUMN OUTCOME VARCHAR(24);
ALTER TABLE MEMBER_NOTIFICATION ADD COLUMN PUSH_COMPLETION_REASON VARCHAR(32);

