CREATE SEQUENCE SOURCE_SYNC_EXECUTION_SEQ START WITH 1 INCREMENT BY 1 NO CYCLE;
CREATE TABLE SOURCE_SYNC_EXECUTION (
    ID BIGINT PRIMARY KEY,
    EXECUTION_ID BIGINT NOT NULL REFERENCES SYNC_EXECUTION(ID),
    SOURCE_SYSTEM VARCHAR(30) NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    STARTED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    FINISHED_AT TIMESTAMP WITH TIME ZONE,
    FETCHED_COUNT INTEGER NOT NULL DEFAULT 0 CHECK (FETCHED_COUNT >= 0),
    SAVED_COUNT INTEGER NOT NULL DEFAULT 0 CHECK (SAVED_COUNT >= 0),
    FAILED_NOTICE_COUNT INTEGER NOT NULL DEFAULT 0 CHECK (FAILED_NOTICE_COUNT >= 0),
    FAILED_UNIT_TYPE_COUNT INTEGER NOT NULL DEFAULT 0 CHECK (FAILED_UNIT_TYPE_COUNT >= 0),
    EMPTY_UNIT_TYPE_COUNT INTEGER NOT NULL DEFAULT 0 CHECK (EMPTY_UNIT_TYPE_COUNT >= 0),
    UNIT_TYPES_DISABLED BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT UK_SOURCE_SYNC_EXECUTION UNIQUE (EXECUTION_ID, SOURCE_SYSTEM),
    CONSTRAINT CK_SOURCE_SYNC_STATUS CHECK (STATUS IN ('RUNNING','SUCCEEDED','PARTIALLY_SUCCEEDED','FAILED','SKIPPED'))
);
CREATE INDEX IX_SOURCE_SYNC_LATEST ON SOURCE_SYNC_EXECUTION (SOURCE_SYSTEM, STARTED_AT DESC, ID DESC);
CREATE INDEX IX_SOURCE_SYNC_SUCCESS ON SOURCE_SYNC_EXECUTION (SOURCE_SYSTEM, STATUS, FINISHED_AT DESC, ID DESC);
