-- Metadata only. Null usage/cost on old or uncertain requests must not mean zero.
ALTER TABLE AI_CONSULTATION_ATTEMPT ADD COLUMN REQUESTED_MODEL VARCHAR(128);
ALTER TABLE AI_CONSULTATION_ATTEMPT ADD COLUMN RESPONSE_MODEL VARCHAR(128);
ALTER TABLE AI_CONSULTATION_ATTEMPT ADD COLUMN INPUT_TOKENS BIGINT CHECK (INPUT_TOKENS >= 0);
ALTER TABLE AI_CONSULTATION_ATTEMPT ADD COLUMN CACHED_INPUT_TOKENS BIGINT CHECK (CACHED_INPUT_TOKENS >= 0);
ALTER TABLE AI_CONSULTATION_ATTEMPT ADD COLUMN OUTPUT_TOKENS BIGINT CHECK (OUTPUT_TOKENS >= 0);
ALTER TABLE AI_CONSULTATION_ATTEMPT ADD COLUMN ESTIMATED_COST_USD NUMERIC(20,8);
ALTER TABLE AI_CONSULTATION_ATTEMPT ADD COLUMN RESERVED_COST_USD NUMERIC(20,8);
ALTER TABLE AI_CONSULTATION_ATTEMPT ADD COLUMN INPUT_RATE NUMERIC(20,8);
ALTER TABLE AI_CONSULTATION_ATTEMPT ADD COLUMN CACHED_INPUT_RATE NUMERIC(20,8);
ALTER TABLE AI_CONSULTATION_ATTEMPT ADD COLUMN OUTPUT_RATE NUMERIC(20,8);
ALTER TABLE AI_CONSULTATION_ATTEMPT ADD COLUMN DURATION_MS BIGINT CHECK (DURATION_MS >= 0);
ALTER TABLE AI_CONSULTATION_ATTEMPT ADD COLUMN FAILURE_TYPE VARCHAR(32);
