CREATE SEQUENCE MEMBER_SEARCH_PREFERENCE_SEQ
    START WITH 1
    INCREMENT BY 1
    NO CYCLE;

CREATE TABLE MEMBER_SEARCH_PREFERENCE (
    ID BIGINT PRIMARY KEY,
    MEMBER_ID BIGINT NOT NULL,
    REGION VARCHAR(40),
    HOUSING_CATEGORY VARCHAR(20),
    STATUS_FILTER VARCHAR(20) NOT NULL,
    SORT_OPTION VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT UK_MEMBER_SEARCH_PREFERENCE UNIQUE (MEMBER_ID),
    CONSTRAINT FK_MEMBER_SEARCH_PREFERENCE_MEMBER FOREIGN KEY (MEMBER_ID)
        REFERENCES APP_MEMBER (ID) ON DELETE CASCADE,
    CONSTRAINT CK_MEMBER_SEARCH_CATEGORY CHECK (
        HOUSING_CATEGORY IS NULL
        OR HOUSING_CATEGORY IN ('APARTMENT', 'PUBLIC_RENTAL', 'OFFICETEL')
    ),
    CONSTRAINT CK_MEMBER_SEARCH_STATUS CHECK (STATUS_FILTER IN ('ALL', 'TODAY', 'OPEN', 'UPCOMING')),
    CONSTRAINT CK_MEMBER_SEARCH_SORT CHECK (SORT_OPTION IN ('LATEST', 'DEADLINE'))
);
