CREATE SEQUENCE MEMBER_NOTIFICATION_PREFERENCE_SEQ
    START WITH 1
    INCREMENT BY 1
    NO CYCLE;

CREATE SEQUENCE MEMBER_NOTIFICATION_SEQ
    START WITH 1
    INCREMENT BY 1
    NO CYCLE;

CREATE TABLE MEMBER_NOTIFICATION_PREFERENCE (
    ID BIGINT PRIMARY KEY,
    MEMBER_ID BIGINT NOT NULL,
    APPLY_START_ENABLED BOOLEAN DEFAULT TRUE NOT NULL,
    DEADLINE_7D_ENABLED BOOLEAN DEFAULT TRUE NOT NULL,
    DEADLINE_3D_ENABLED BOOLEAN DEFAULT TRUE NOT NULL,
    DEADLINE_1D_ENABLED BOOLEAN DEFAULT TRUE NOT NULL,
    WINNER_ENABLED BOOLEAN DEFAULT TRUE NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT UK_MEMBER_NOTIFICATION_PREFERENCE UNIQUE (MEMBER_ID),
    CONSTRAINT FK_MEMBER_NOTIFICATION_PREFERENCE_MEMBER FOREIGN KEY (MEMBER_ID)
        REFERENCES APP_MEMBER (ID) ON DELETE CASCADE
);

CREATE TABLE MEMBER_NOTIFICATION (
    ID BIGINT PRIMARY KEY,
    MEMBER_ID BIGINT NOT NULL,
    NOTICE_ID BIGINT NOT NULL,
    NOTIFICATION_TYPE VARCHAR(30) NOT NULL,
    EVENT_DATE DATE NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    READ_AT TIMESTAMP WITH TIME ZONE,
    CONSTRAINT UK_MEMBER_NOTIFICATION_EVENT UNIQUE (
        MEMBER_ID,
        NOTICE_ID,
        NOTIFICATION_TYPE,
        EVENT_DATE
    ),
    CONSTRAINT FK_MEMBER_NOTIFICATION_MEMBER FOREIGN KEY (MEMBER_ID)
        REFERENCES APP_MEMBER (ID) ON DELETE CASCADE,
    CONSTRAINT FK_MEMBER_NOTIFICATION_NOTICE FOREIGN KEY (NOTICE_ID)
        REFERENCES SUBSCRIPTION_NOTICE (ID) ON DELETE CASCADE,
    CONSTRAINT CK_MEMBER_NOTIFICATION_TYPE CHECK (
        NOTIFICATION_TYPE IN (
            'APPLY_START',
            'APPLY_DEADLINE_7D',
            'APPLY_DEADLINE_3D',
            'APPLY_DEADLINE_1D',
            'WINNER_ANNOUNCEMENT'
        )
    )
);

CREATE INDEX IX_MEMBER_NOTIFICATION_INBOX
    ON MEMBER_NOTIFICATION (MEMBER_ID, READ_AT, CREATED_AT DESC);
