CREATE SEQUENCE MEMBER_RECOMMENDATION_DISMISSAL_SEQ
    START WITH 1
    INCREMENT BY 1
    NO CYCLE;

CREATE TABLE MEMBER_RECOMMENDATION_DISMISSAL (
    ID BIGINT PRIMARY KEY,
    MEMBER_ID BIGINT NOT NULL,
    NOTICE_ID BIGINT NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT UK_MEMBER_RECOMMENDATION_DISMISSAL UNIQUE (MEMBER_ID, NOTICE_ID),
    CONSTRAINT FK_RECOMMENDATION_DISMISSAL_MEMBER FOREIGN KEY (MEMBER_ID)
        REFERENCES APP_MEMBER (ID) ON DELETE CASCADE,
    CONSTRAINT FK_RECOMMENDATION_DISMISSAL_NOTICE FOREIGN KEY (NOTICE_ID)
        REFERENCES SUBSCRIPTION_NOTICE (ID) ON DELETE CASCADE
);

CREATE INDEX IX_RECOMMENDATION_DISMISSAL_MEMBER
    ON MEMBER_RECOMMENDATION_DISMISSAL (MEMBER_ID);
