CREATE SEQUENCE MEMBER_COMPARISON_SEQ
    START WITH 1
    INCREMENT BY 1
    NO CYCLE;

CREATE TABLE MEMBER_COMPARISON (
    ID BIGINT PRIMARY KEY,
    MEMBER_ID BIGINT NOT NULL,
    NOTICE_ID BIGINT NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT UK_MEMBER_COMPARISON UNIQUE (MEMBER_ID, NOTICE_ID),
    CONSTRAINT FK_MEMBER_COMPARISON_MEMBER FOREIGN KEY (MEMBER_ID)
        REFERENCES APP_MEMBER (ID) ON DELETE CASCADE,
    CONSTRAINT FK_MEMBER_COMPARISON_NOTICE FOREIGN KEY (NOTICE_ID)
        REFERENCES SUBSCRIPTION_NOTICE (ID) ON DELETE CASCADE
);

CREATE INDEX IX_MEMBER_COMPARISON_MEMBER
    ON MEMBER_COMPARISON (MEMBER_ID, CREATED_AT, ID);
