ALTER TABLE APP_MEMBER
    ADD COLUMN EMAIL_VERIFIED_AT TIMESTAMP WITH TIME ZONE;

UPDATE APP_MEMBER
SET EMAIL_VERIFIED_AT = CREATED_AT
WHERE EMAIL_VERIFIED_AT IS NULL;

CREATE SEQUENCE MEMBER_ACTION_TOKEN_SEQ START WITH 1 INCREMENT BY 1 NO CYCLE;

CREATE TABLE MEMBER_ACTION_TOKEN (
    ID BIGINT PRIMARY KEY,
    MEMBER_ID BIGINT NOT NULL,
    TOKEN_TYPE VARCHAR(30) NOT NULL,
    TOKEN_HASH VARCHAR(64) NOT NULL,
    EXPIRES_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT UK_MEMBER_ACTION_TOKEN_HASH UNIQUE (TOKEN_HASH),
    CONSTRAINT UK_MEMBER_ACTION_TOKEN_TYPE UNIQUE (MEMBER_ID, TOKEN_TYPE),
    CONSTRAINT CK_MEMBER_ACTION_TOKEN_TYPE CHECK (TOKEN_TYPE IN ('EMAIL_VERIFICATION', 'PASSWORD_RESET')),
    CONSTRAINT FK_MEMBER_ACTION_TOKEN_MEMBER FOREIGN KEY (MEMBER_ID)
        REFERENCES APP_MEMBER (ID) ON DELETE CASCADE
);

CREATE INDEX IX_MEMBER_ACTION_TOKEN_EXPIRY ON MEMBER_ACTION_TOKEN (EXPIRES_AT);
